'''
Tool for generating assignments and tests based on payload

{
  "title": "Title of an assignment",
  "description": "- This description\n- Supports **markdown**",
  "tests": {
    "shown": [
      {
        "input": "[1,2,3,4,5]",
        "output": "1",
        "group": "group1"
      }
    ],
    "hidden":[{}]
  },
  "function_name": "get_minimum"
}
'''

import json

def generate_assignment(json_payload, template_path=None):
    '''
    Create and return markdown based on json_payload and provided template

    Example of json_payload:\n
    {
        "title": "str-md",
        "description": "str-md",
        "tests": {
            "shown": [
                {
                    "input": "str",
                    "output": "str",
                    "group": "str"
                }
            ]
        },
        "function_name": "str"
    }

    Template must include:
    - {title}
    - {description}
    - {function_name}
    - {input_output_table}
        - |{input}|{output}| for each test case
    '''

    assignment = ''
    with open(template_path) as template_file:
        assignment = template_file.read()

    data = json.loads(json_payload)
    input_output_list = [(x.get('input'), x.get('output')) for x in data['tests']['shown']]
    input_output_table = '\n'.join([f'|{x}|{y}|' for (x,y) in input_output_list])

    data["input_output_table"] = input_output_table
    assignment = assignment.format(**data)
    
    return assignment



def generate_tests(json_payload):
    '''
    Returns usable test file as a string

    Each test case is one assertion
    Assertions are grouped in separated test functions
    '''



def main():
    '''
    Used for testing module functions
    '''
    test_data = '{\"title\":\"Title of an assignment\",\"description\":\"- This description\\n- Supports **markdown**\",\"tests\":{\"shown\":[{\"input\":\"[1,2,3,4,5]\",\"output\":\"1\",\"group\":\"group1\"},{\"input\":\"[1,2,3,4,5,232,-1,232,2]\",\"output\":\"-1\",\"group\":\"group1\"}]},\"function_name\":\"get_minimum\"}'

    with open('autogenerated_markdown.md', 'w') as file:
        file.write(generate_assignment(test_data, './resources/assignment_template.md'))

if __name__ == "__main__":
    main()
