# Autogenerated code

import importlib
import sys

module = importlib.import_module(sys.argv[1])

def test_case_group1(fn):
    try:
        assert fn("str", 3) == "strstrstr"
        assert fn("2", 2) == "22"
        return True
    except:
        return False

def test_case_group2(fn):
    try:
        assert fn("", 3) == ""
        assert fn("2", 0) == ""
        return True
    except:
        return False

def main():
    list = [test_case_group1(module.simple_repeater),test_case_group2(module.simple_repeater)]
    success = list.count(True)
    fail = len(list) - success
    print(success,fail)
    

if __name__ == "__main__":
    main()
